local map = vim.keymap.set

map("n", "<Esc>", "<cmd>nohlsearch<CR>")
map("n", "<leader>w", "<cmd>w<CR>", { desc = "Save file" })
map("n", "<leader>q", "<cmd>q<CR>", { desc = "Quit window" })
map("n", "<leader>Q", "<cmd>qa!<CR>", { desc = "Quit all" })
map("n", "<leader>e", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file tree" })
map("n", "<leader>E", "<cmd>NvimTreeFindFile<CR>", { desc = "Reveal current file in tree" })
map("n", "<leader>ef", "<cmd>NvimTreeFocus<CR>", { desc = "Focus file tree" })
map("n", "<leader>pp", "<cmd>Telescope projects<CR>", { desc = "Projects" })
map("n", "<leader>ps", "<cmd>lua require('persistence').load()<CR>", { desc = "Restore session" })
map("n", "<leader>pl", "<cmd>lua require('persistence').load({ last = true })<CR>", { desc = "Restore last session" })
map("n", "<leader>pd", "<cmd>lua require('persistence').stop()<CR>", { desc = "Stop session save" })
map("n", "<leader>ss", "<cmd>lua require('persistence').save()<CR>", { desc = "Save session" })
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle focus=true<CR>", { desc = "Diagnostics list" })
map("n", "<leader>xq", "<cmd>Trouble quickfix toggle focus=true<CR>", { desc = "Quickfix list" })
map("n", "<leader>xl", "<cmd>Trouble loclist toggle focus=true<CR>", { desc = "Location list" })
map("n", "<leader>xL", "<cmd>lopen<CR>", { desc = "Open location list" })
map("n", "<leader>xQ", "<cmd>copen<CR>", { desc = "Open quickfix list" })
map("n", "<C-h>", "<C-w>h", { desc = "Move to left split" })
map("n", "<C-j>", "<C-w>j", { desc = "Move to lower split" })
map("n", "<C-k>", "<C-w>k", { desc = "Move to upper split" })
map("n", "<C-l>", "<C-w>l", { desc = "Move to right split" })
map("n", "<leader>sv", "<cmd>vsplit<CR>", { desc = "Vertical split" })
map("n", "<leader>sh", "<cmd>split<CR>", { desc = "Horizontal split" })
map("n", "<leader>se", "<cmd>wincmd =<CR>", { desc = "Equalize splits" })
map("n", "<leader>sc", "<cmd>close<CR>", { desc = "Close split" })
map("n", "<leader>ff", "<cmd>Telescope find_files hidden=true<CR>", { desc = "Find files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Live grep" })
map("n", "<leader>fb", "<cmd>Telescope buffers<CR>", { desc = "Buffers" })
map("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", { desc = "Help" })
map("n", "<leader>fr", "<cmd>Telescope resume<CR>", { desc = "Resume search" })
map("n", "<leader>fd", "<cmd>Telescope diagnostics<CR>", { desc = "Diagnostics" })
map("n", "<leader>lf", "<cmd>Format<CR>", { desc = "Format buffer" })
map("n", "<leader>gb", "<cmd>Gitsigns blame_line<CR>", { desc = "Git blame line" })
map("n", "<leader>gp", "<cmd>Gitsigns preview_hunk<CR>", { desc = "Preview hunk" })
map("n", "<leader>gs", "<cmd>Gitsigns stage_hunk<CR>", { desc = "Stage hunk" })
map("n", "<leader>gr", "<cmd>Gitsigns reset_hunk<CR>", { desc = "Reset hunk" })
map("n", "<leader>td", "<cmd>TodoTelescope<CR>", { desc = "Todo search" })
