return {
  require("plugins.ui"),
  require("plugins.core"),
  require("plugins.files"),
  require("plugins.telescope"),
  require("plugins.navigation"),
  require("plugins.treesitter"),
  require("plugins.completion"),
  require("plugins.lsp"),
  require("plugins.formatting"),
  require("plugins.git"),
  require("plugins.gitview"),
  require("plugins.appdev"),
  require("plugins.tasks"),
  require("plugins.dap"),
}
